# Generated by Django 5.0.6 on 2024-05-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.document')),
            ],
            options={
                'verbose_name': 'Nugget',
                'verbose_name_plural': 'Nuggets',
            },
        ),
        migrations.CreateModel(
            name='BoxAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(blank=True, default=0)),
                ('downvotes', models.IntegerField(blank=True, default=0)),
                ('manually_confirmed', models.BooleanField(blank=True, default=False)),
                ('box_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.boxattribute')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.document')),
                ('nugget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nugget')),
            ],
            options={
                'verbose_name': 'Box Attribute Value',
                'verbose_name_plural': 'Box Attribute Values',
            },
        ),
    ]
