# Generated by Django 5.0.6 on 2024-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_nugget_boxattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='box_rows',
            field=models.ManyToManyField(through='web.BoxAttributeValue', to='web.boxattribute'),
        ),
    ]
