# Generated by Django 5.0.6 on 2024-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_document_box_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxattributevalue',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
