# Generated by Django 5.0.6 on 2024-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_boxattributevalue_confidence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxattributevalue',
            unique_together={('box_attribute', 'document')},
        ),
    ]
