# Generated by Django 5.0.6 on 2024-05-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_boxattributevalue_nugget'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuggetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Nugget Label',
                'verbose_name_plural': 'Nugget Labels',
            },
        ),
        migrations.AddField(
            model_name='nugget',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.nuggetlabel'),
        ),
    ]
