# Generated by Django 5.0.6 on 2024-05-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_nuggetlabel_nugget_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nugget',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nuggetlabel'),
        ),
    ]
