# Generated by Django 4.2.13 on 2024-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_nugget_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='docbase_file_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, path='/'),
        ),
    ]
